
FROM node:13.12.0-alpine

# set working directory
WORKDIR /var/www/html/exam_server

# add `/var/www/html/exam_server/node_modules/.bin` to $PATH
ENV PATH /var/www/html/exam_server/node_modules/.bin:$PATH

# install app dependencies
COPY . ./
RUN apk add --update python make g++\
    && rm -rf /var/cache/apk/*
RUN npm install --silent
RUN npm i --save --save-exact bcrypt

# add app
EXPOSE 8000:8000


# start app
CMD ["npm", "run prod"]